version: "3.3"
services:
  redis: # Name of the first service
    image: redis  # Use Redis image from Docker Hub
    ports:
      - 6379:6379 # Expose port 6379 of the container to the host machine

  api:  # Name of the second service
    depends_on:
      - redis   # Nom du conteneur sur lequel il dépend
    image: python-redis-app
    ports:
      - "5000:5000"   # Expose port 5000 of the container to the host machine
    restart: always   # redémarre automatiquement le conteneur si il s'arrête



### COMMANDS TERMINAL

## Start both services:
#=>  docker-compose up -d

## Stop both services:
#=> docker-compose stop

## Start using the app at this URL:
#=> http://localhost:5000/